# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 755e17970bee631051cb39891e7e15a67e5be75cd4d3f71b92734725f7d807ab8b9b85daa83e6cb00475280d0ce29a601e23d54e284f50b5e2ddd81647c1ece1

test:
  secret_key_base: 3086c51e2558ae096f85c8a8ea7619b5f48529b0a741e0175d124cfe9eac676be8ba9c3eaf00462b2281cec33f6c3c32ed13af47f1c5a3e09e9a570e00ebd07a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
